{
 "title": "1-Sensor",
 "time": { "from": "now-2d", "to": "now-0s" },
 "panels": [
  {
   "title": "pH",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "SensorReadings",
     "query": "SELECT \"value\" FROM \"SensorReadings\" WHERE \"sensor\" = 'ph' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "ph" }
     ]
    }
   ]
  },
  {
   "title": "Water Level",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "SensorReadings",
     "query": "SELECT \"value\" FROM \"SensorReadings\" WHERE \"sensor\" = 'waterLevel' AND \"type\" = 'range' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "waterLevel" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "range" }
     ]
    }
   ]
  },
  {
   "title": "EC",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "SensorReadings",
     "query": "SELECT \"value\" FROM \"SensorReadings\" WHERE \"sensor\" = 'ec' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "ec" }
     ]
    }
   ]
  },
  {
   "title": "Temp",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "format": "farenheit",
   "valueName": "current",
   "targets": [
    {
     "measurement": "SensorReadings",
     "query": "SELECT \"value\" FROM \"SensorReadings\" WHERE \"sensor\" = 'temperature' AND \"type\" = 'tank' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "temperature" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "tank" }
     ]
    }
   ]
  },
  {
   "title": "Lights",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_id]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "lights",
     "query": "SELECT last(\"value\") FROM \"lights\" WHERE $timeFilter GROUP BY time($interval), \"id\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sensor Readings",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_sensor]] - [[tag_type]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "SensorReadings",
     "query": "SELECT mean(\"value\") FROM \"SensorReadings\" WHERE $timeFilter GROUP BY time($interval), \"sensor\", \"type\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tank Temp",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "alias": "Tank Temp",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SensorReadings",
     "query": "SELECT \"value\" FROM \"SensorReadings\" WHERE \"sensor\" = 'temperature' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tank" }
     ]
    },
    {
     "alias": "Air / Temp",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SensorReadings",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "temperature" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "esp" }
     ]
    },
    {
     "alias": "Air / Humidity",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SensorReadings",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "humidity" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "esp" }
     ]
    }
   ]
  },
  {
   "title": "Water Level",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Water Level [[tag_type]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "SensorReadings",
     "query": "SELECT last(\"value\") FROM \"SensorReadings\" WHERE \"sensor\" = 'waterLevel' AND $timeFilter GROUP BY time($interval), \"type\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "waterLevel" }
     ]
    }
   ]
  },
  {
   "title": "EC",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "EC",
     "measurement": "SensorReadings",
     "query": "SELECT last(\"value\") FROM \"lights\" WHERE $timeFilter GROUP BY time($interval), \"id\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "ec" }
     ]
    }
   ]
  },
  {
   "title": "PH",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "PH",
     "measurement": "SensorReadings",
     "query": "SELECT last(\"value\") FROM \"SensorReadings\" WHERE \"sensor\" = 'waterLevel' AND $timeFilter GROUP BY time($interval), \"type\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "ph" }
     ]
    }
   ]
  },
  {
   "title": "Relays",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_number]] - [[tag_name]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "number" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "relays",
     "query": "SELECT last(\"value\") FROM \"relays\" WHERE \"relay\" = 'sain8' AND $timeFilter GROUP BY time($interval), \"number\", \"name\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "relay", "operator": "=", "value": "sain8" }
     ]
    }
   ]
  },
  {
   "title": "Manual Readings",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_test]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "test" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ManualReadings",
     "query": "SELECT last(\"value\") FROM \"ManualReadings\" WHERE $timeFilter GROUP BY time($interval), \"test\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Environment",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_sensor]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Environment",
     "query": "SELECT \"value\" FROM \"SensorReadings\" WHERE \"sensor\" = 'temperature' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "esp" }
     ]
    }
   ]
  }
 ]
}